/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini.datastructure;

public class Node<K> {
	private Node next;
	private K key;

	public Node(K key) {
		this.key = key;
		this.setNext(null);
	}

	public Node getNext() {
		return next;
	}

	public void setNext(Node next) {
		this.next = next;
	}
}
